start-at-login = true

after-login-command = []
after-startup-command = []

accordion-padding = 0

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal = 8
inner.vertical = 8
outer.left = 8
outer.bottom = 8
outer.top = 8
outer.right = 8

[mode.main.binding]
cmd-alt-leftSquareBracket = 'layout accordion horizontal vertical'
cmd-alt-rightSquareBracket = 'layout tiles horizontal'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Focus cycle approximation
cmd-alt-j = 'focus dfs-next'
cmd-alt-k = 'focus dfs-prev'

cmd-alt-h = 'resize width -50'
cmd-alt-l = 'resize width +50'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'

alt-tab = 'workspace-back-and-forth'
